name: Self-install labels (dogfood)

on:
  workflow_dispatch:

jobs:
  install:
    uses: convergent-systems-co/repo-standards/.github/workflows/label-install.yml@545dc22e6d2905daef6d3f42780e0f456fd09101
    with:
      labels-ref: main
      delete-others: false
